#!/bin/bash
set -e

BASE=$(dirname $0)/..
LELUX=$BASE/lelux

qemu-system-x86_64 -enable-kvm \
    -netdev user,id=nat -device virtio-net-pci,netdev=nat \
    -kernel $BASE/vmlinuz-3.8.0 \
    -initrd $LELUX.cpio.gz \
    /dev/zero
